# curl -X POST -H "Content-Type: application/json" -d '{"mode": 0, "text": "ciao"}' http://192.168.1.143:8080/displayMessage
POST http://192.168.1.143:8080/displayMessage
Content-Type: application/json

{"mode": 0, "text": "ciao"}

###

