# curl -X POST -H "Content-Type: application/json" -d '{"mode": 0, "text": "ciao"}' http://192.168.1.143:8080/display_message
POST http://raspberrypi:8080/display_message
Content-Type: application/json

{"mode": 0, "text": "hola"}

###

GET http://raspberrypi:8080/list_assets
http://192.168.1.144:8080/list_assets
###

